version: '3.8'
services:
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: transparencia
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:6
    ports:
      - '6379:6379'

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    environment:
      - discovery.type=single-node
      - cluster.name=opensearch-cluster
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
      - '9600:9600'
    volumes:
      - opensearch_data:/usr/share/opensearch/data

volumes:
  mariadb_data:
  opensearch_data:
